# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter I01WD,$(TARGET_DEVICE)),)

endif
